name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  dart_frog: ^0.3.7
  mongo_dart: ^0.9.1
  uuid: ^3.0.7
  models:
    path: models
  aws_common: ^0.5.0+1
  aws_signature_v4: ^0.4.0+1
  aws_dynamodb_api: ^2.0.0
  http: ^0.13.6
  dart_frog_web_socket: ^0.1.0-dev.3
  riverpod: ^2.3.6
  dotenv: ^4.1.0


dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
