targets:
  $default:
    builders:
      json_serializable:
        options:
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          ignore_unannotated: false