name: norma_app

#concurrency:
#  group: $-$
#  cancel-in-progress: true

on:
  push:
    branches:
      - none

jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.10.x"
          channel: "stable"
          cache: true

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: dart format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Install very_good cli
        run: dart pub global activate very_good_cli

      - name: Run tests
        run: very_good test --coverage --min-coverage 60
